# Generated by Django 6.0.2 on 2026-07-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_class_term_type_alter_term_term_type_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_enrolled',
        ),
        migrations.AddField(
            model_name='student',
            name='classes_enrolled',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students', to='classes.class'),
        ),
    ]
