# Generated by Django 6.0.2 on 2026-06-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='days',
            field=models.CharField(default='monday', help_text="Comma-separated days (e.g., 'monday,wednesday,friday')", max_length=200),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='slot_type',
            field=models.CharField(choices=[('morning', 'Morning (8:00 - 11:00)'), ('afternoon', 'Afternoon (2:00 - 5:00)'), ('evening', 'Evening (5:30 - 8:45)'), ('full_day', 'Full Day (8:00 - 5:00)'), ('half_day', 'Half Day (8:00 - 12:00)'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='day',
        ),
    ]
