# Generated by Django 6.0.2 on 2026-07-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_timeslot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='term_type',
            field=models.CharField(blank=True, choices=[('semester1', 'Semester 1'), ('semester2', 'Semester 2')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_type',
            field=models.CharField(choices=[('semester1', 'Semester 1'), ('semester2', 'Semester 2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='slot_type',
            field=models.CharField(choices=[('morning', 'Morning Session (8:00 - 11:00)'), ('afternoon', 'Afternoon Session (2:00 - 5:00)'), ('evening', 'Evening Session (5:30 - 8:45)'), ('full_day', 'Full Day (8:00 - 5:00)'), ('saturday_morning', 'Saturday Morning (8:00 - 11:00)'), ('saturday_afternoon', 'Saturday Afternoon (2:00 - 5:00)'), ('sunday_morning', 'Sunday Morning (8:00 - 11:00)'), ('sunday_afternoon', 'Sunday Afternoon (2:00 - 5:00)'), ('weekend_full', 'Weekend Full Day (8:00 - 5:00)'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
    ]
