# Generated by Django 6.0.2 on 2026-07-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_class_term_type_alter_term_term_type_and_more'),
        ('courses', '0003_course_time_slots_alter_course_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='course',
        ),
        migrations.AddField(
            model_name='class',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='class_offerings', to='courses.course'),
        ),
    ]
