# Generated by Django 6.0.2 on 2026-07-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(default='12 weeks', max_length=50),
        ),
    ]
