# Generated by Django 6.0.2 on 2026-07-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_class_term_type_alter_term_term_type_and_more'),
        ('courses', '0002_alter_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time_slots',
            field=models.ManyToManyField(blank=True, related_name='courses', to='classes.timeslot'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('100', 'Year 1'), ('200', 'Year 2'), ('300', 'Year 3'), ('400', 'Year 4'), ('500', 'Year 5')], default='100', max_length=10),
        ),
    ]
