# Generated by Django 6.0.2 on 2026-07-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_class_course_class_courses'),
        ('courses', '0003_course_time_slots_alter_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='course_classes', to='classes.class'),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_slots',
            field=models.ManyToManyField(blank=True, related_name='course_time_slots', to='classes.timeslot'),
        ),
    ]
