# Generated by Django 6.0.2 on 2026-07-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_classes_alter_course_time_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='classes',
        ),
    ]
